/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_javalite_Context */

#ifndef _Included_com_baidu_javalite_Context
#define _Included_com_baidu_javalite_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_user_data
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_baidu_javalite_Context_sqlite3_1user_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_context_db_handle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_javalite_Context_sqlite3_1context_1db_1handle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_aggregate_context
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1aggregate_1context__JLjava_lang_Object_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_aggregate_context
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_baidu_javalite_Context_sqlite3_1aggregate_1context__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_aggregate_context_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1aggregate_1context_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
