/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_javalite_Database */

#ifndef _Included_com_baidu_javalite_Database
#define _Included_com_baidu_javalite_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_open_v2
 * Signature: (Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_javalite_Database_sqlite3_1open_1v2
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_threadsafe
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_javalite_Database_sqlite3_1threadsafe
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_threadmode_config
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Database_sqlite3_1threadmode_1config
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Database_sqlite3_1initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Database_sqlite3_1shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_libversion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_Database_sqlite3_1libversion
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_sourceid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_Database_sqlite3_1sourceid
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_libversion_number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_Database_sqlite3_1libversion_1number
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_complete
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_javalite_Database_sqlite3_1complete
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
