/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_javalite_Value */

#ifndef _Included_com_baidu_javalite_Value
#define _Included_com_baidu_javalite_Value
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_javalite_Value
 * Method:    sqlite3_value_blob
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_baidu_javalite_Value_sqlite3_1value_1blob
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Value
 * Method:    sqlite3_value_double
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_baidu_javalite_Value_sqlite3_1value_1double
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Value
 * Method:    sqlite3_value_int
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_Value_sqlite3_1value_1int
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Value
 * Method:    sqlite3_value_int64
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_javalite_Value_sqlite3_1value_1int64
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Value
 * Method:    sqlite3_value_text
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_Value_sqlite3_1value_1text
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Value
 * Method:    sqlite3_value_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_Value_sqlite3_1value_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Value
 * Method:    sqlite3_value_numeric_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_Value_sqlite3_1value_1numeric_1type
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
