/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_javalite_Blob */

#ifndef _Included_com_baidu_javalite_Blob
#define _Included_com_baidu_javalite_Blob
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_javalite_Blob
 * Method:    sqlite3_blob_open
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_javalite_Blob_sqlite3_1blob_1open
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jlong, jint);

/*
 * Class:     com_baidu_javalite_Blob
 * Method:    sqlite3_blob_reopen
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Blob_sqlite3_1blob_1reopen
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_baidu_javalite_Blob
 * Method:    sqlite3_blob_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Blob_sqlite3_1blob_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Blob
 * Method:    sqlite3_blob_bytes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_Blob_sqlite3_1blob_1bytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Blob
 * Method:    sqlite3_blob_read
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Blob_sqlite3_1blob_1read
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_baidu_javalite_Blob
 * Method:    sqlite3_blob_write
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Blob_sqlite3_1blob_1write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
