/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_javalite_Database */

#ifndef _Included_com_baidu_javalite_Database
#define _Included_com_baidu_javalite_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_open_v2
 * Signature: (Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_javalite_Database_sqlite3_1open_1v2
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_baidu_javalite_Database
 * Method:    sqlite3_threadsafe
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_javalite_Database_sqlite3_1threadsafe
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
