/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_javalite_PrepareStmt */

#ifndef _Included_com_baidu_javalite_PrepareStmt
#define _Included_com_baidu_javalite_PrepareStmt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_type
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1type
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_text
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1text
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_int64
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1int64
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_int
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1int
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_double
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1double
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_blob
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1blob
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_data_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1data_1count
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_decltype
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1decltype
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_origin_name
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1origin_1name
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_table_name
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1table_1name
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_database_name
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1database_1name
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_name
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1name
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_column_count
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1column_1count
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_step
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1step
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1finalize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_PrepareStmt
 * Method:    sqlite3_reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_PrepareStmt_sqlite3_1reset
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
