/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_javalite_Context */

#ifndef _Included_com_baidu_javalite_Context
#define _Included_com_baidu_javalite_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_user_data
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_baidu_javalite_Context_sqlite3_1user_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_context_db_handle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_javalite_Context_sqlite3_1context_1db_1handle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_aggregate_context
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1aggregate_1context__JLjava_lang_Object_2
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_aggregate_context
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_baidu_javalite_Context_sqlite3_1aggregate_1context__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_aggregate_context_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1aggregate_1context_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_result_double
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1result_1double
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_result_int
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1result_1int
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_result_int64
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1result_1int64
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_result_null
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1result_1null
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_result_text
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1result_1text
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_result_blob
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1result_1blob
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_result_zeroblob
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1result_1zeroblob
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_baidu_javalite_Context
 * Method:    sqlite3_result_value
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_baidu_javalite_Context_sqlite3_1result_1value
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
